# permissions for end users to view bridgeinformation.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bridgeinformation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bridge-operator
    app.kubernetes.io/part-of: bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: bridgeinformation-viewer-role
rules:
- apiGroups:
  - bridgeoperator.k8s.cni.npwg.io
  resources:
  - bridgeinformation
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bridgeoperator.k8s.cni.npwg.io
  resources:
  - bridgeinformation/status
  verbs:
  - get
