# permissions for end users to edit bridgeconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bridgeconfiguration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bridge-operator
    app.kubernetes.io/part-of: bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: bridgeconfiguration-editor-role
rules:
- apiGroups:
  - bridgeoperator.k8s.cni.npwg.io
  resources:
  - bridgeconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bridgeoperator.k8s.cni.npwg.io
  resources:
  - bridgeconfigurations/status
  verbs:
  - get
