/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/k8snetworkplumbingwg/bridge-operator/api/bridgeoperator.k8s.cni.npwg.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBridgeInformations implements BridgeInformationInterface
type FakeBridgeInformations struct {
	Fake *FakeBridgeoperatorV1alpha1
}

var bridgeinformationsResource = schema.GroupVersionResource{Group: "bridgeoperator.k8s.cni.npwg.io", Version: "v1alpha1", Resource: "bridgeinformation"}

var bridgeinformationsKind = schema.GroupVersionKind{Group: "bridgeoperator.k8s.cni.npwg.io", Version: "v1alpha1", Kind: "BridgeInformation"}

// Get takes name of the bridgeInformation, and returns the corresponding bridgeInformation object, and an error if there is any.
func (c *FakeBridgeInformations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BridgeInformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bridgeinformationsResource, name), &v1alpha1.BridgeInformation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeInformation), err
}

// List takes label and field selectors, and returns the list of BridgeInformations that match those selectors.
func (c *FakeBridgeInformations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BridgeInformationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bridgeinformationsResource, bridgeinformationsKind, opts), &v1alpha1.BridgeInformationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BridgeInformationList{ListMeta: obj.(*v1alpha1.BridgeInformationList).ListMeta}
	for _, item := range obj.(*v1alpha1.BridgeInformationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bridgeInformations.
func (c *FakeBridgeInformations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bridgeinformationsResource, opts))
}

// Create takes the representation of a bridgeInformation and creates it.  Returns the server's representation of the bridgeInformation, and an error, if there is any.
func (c *FakeBridgeInformations) Create(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.CreateOptions) (result *v1alpha1.BridgeInformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bridgeinformationsResource, bridgeInformation), &v1alpha1.BridgeInformation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeInformation), err
}

// Update takes the representation of a bridgeInformation and updates it. Returns the server's representation of the bridgeInformation, and an error, if there is any.
func (c *FakeBridgeInformations) Update(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (result *v1alpha1.BridgeInformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bridgeinformationsResource, bridgeInformation), &v1alpha1.BridgeInformation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeInformation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBridgeInformations) UpdateStatus(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (*v1alpha1.BridgeInformation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bridgeinformationsResource, "status", bridgeInformation), &v1alpha1.BridgeInformation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeInformation), err
}

// Delete takes name of the bridgeInformation and deletes it. Returns an error if one occurs.
func (c *FakeBridgeInformations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bridgeinformationsResource, name, opts), &v1alpha1.BridgeInformation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBridgeInformations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bridgeinformationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BridgeInformationList{})
	return err
}

// Patch applies the patch and returns the patched bridgeInformation.
func (c *FakeBridgeInformations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BridgeInformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bridgeinformationsResource, name, pt, data, subresources...), &v1alpha1.BridgeInformation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeInformation), err
}
