/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/k8snetworkplumbingwg/bridge-operator/api/bridgeoperator.k8s.cni.npwg.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBridgeConfigurations implements BridgeConfigurationInterface
type FakeBridgeConfigurations struct {
	Fake *FakeBridgeoperatorV1alpha1
}

var bridgeconfigurationsResource = schema.GroupVersionResource{Group: "bridgeoperator.k8s.cni.npwg.io", Version: "v1alpha1", Resource: "bridgeconfigurations"}

var bridgeconfigurationsKind = schema.GroupVersionKind{Group: "bridgeoperator.k8s.cni.npwg.io", Version: "v1alpha1", Kind: "BridgeConfiguration"}

// Get takes name of the bridgeConfiguration, and returns the corresponding bridgeConfiguration object, and an error if there is any.
func (c *FakeBridgeConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BridgeConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bridgeconfigurationsResource, name), &v1alpha1.BridgeConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeConfiguration), err
}

// List takes label and field selectors, and returns the list of BridgeConfigurations that match those selectors.
func (c *FakeBridgeConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BridgeConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bridgeconfigurationsResource, bridgeconfigurationsKind, opts), &v1alpha1.BridgeConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BridgeConfigurationList{ListMeta: obj.(*v1alpha1.BridgeConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.BridgeConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bridgeConfigurations.
func (c *FakeBridgeConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bridgeconfigurationsResource, opts))
}

// Create takes the representation of a bridgeConfiguration and creates it.  Returns the server's representation of the bridgeConfiguration, and an error, if there is any.
func (c *FakeBridgeConfigurations) Create(ctx context.Context, bridgeConfiguration *v1alpha1.BridgeConfiguration, opts v1.CreateOptions) (result *v1alpha1.BridgeConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bridgeconfigurationsResource, bridgeConfiguration), &v1alpha1.BridgeConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeConfiguration), err
}

// Update takes the representation of a bridgeConfiguration and updates it. Returns the server's representation of the bridgeConfiguration, and an error, if there is any.
func (c *FakeBridgeConfigurations) Update(ctx context.Context, bridgeConfiguration *v1alpha1.BridgeConfiguration, opts v1.UpdateOptions) (result *v1alpha1.BridgeConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bridgeconfigurationsResource, bridgeConfiguration), &v1alpha1.BridgeConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeConfiguration), err
}

// Delete takes name of the bridgeConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeBridgeConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bridgeconfigurationsResource, name, opts), &v1alpha1.BridgeConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBridgeConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bridgeconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BridgeConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched bridgeConfiguration.
func (c *FakeBridgeConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BridgeConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bridgeconfigurationsResource, name, pt, data, subresources...), &v1alpha1.BridgeConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeConfiguration), err
}
