//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Kubernetes Network Plumbing Working Group

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeConfiguration) DeepCopyInto(out *BridgeConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeConfiguration.
func (in *BridgeConfiguration) DeepCopy() *BridgeConfiguration {
	if in == nil {
		return nil
	}
	out := new(BridgeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeConfigurationList) DeepCopyInto(out *BridgeConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BridgeConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeConfigurationList.
func (in *BridgeConfigurationList) DeepCopy() *BridgeConfigurationList {
	if in == nil {
		return nil
	}
	out := new(BridgeConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeConfigurationSpec) DeepCopyInto(out *BridgeConfigurationSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.EgressVlanInterfaces != nil {
		in, out := &in.EgressVlanInterfaces, &out.EgressVlanInterfaces
		*out = make([]EgressVlanInterface, len(*in))
		copy(*out, *in)
	}
	if in.EgressInterfaces != nil {
		in, out := &in.EgressInterfaces, &out.EgressInterfaces
		*out = make([]EgressInterface, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeConfigurationSpec.
func (in *BridgeConfigurationSpec) DeepCopy() *BridgeConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(BridgeConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInformation) DeepCopyInto(out *BridgeInformation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInformation.
func (in *BridgeInformation) DeepCopy() *BridgeInformation {
	if in == nil {
		return nil
	}
	out := new(BridgeInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeInformation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInformationList) DeepCopyInto(out *BridgeInformationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BridgeInformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInformationList.
func (in *BridgeInformationList) DeepCopy() *BridgeInformationList {
	if in == nil {
		return nil
	}
	out := new(BridgeInformationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeInformationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInformationPortStatus) DeepCopyInto(out *BridgeInformationPortStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInformationPortStatus.
func (in *BridgeInformationPortStatus) DeepCopy() *BridgeInformationPortStatus {
	if in == nil {
		return nil
	}
	out := new(BridgeInformationPortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInformationStatus) DeepCopyInto(out *BridgeInformationStatus) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]BridgeInformationPortStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInformationStatus.
func (in *BridgeInformationStatus) DeepCopy() *BridgeInformationStatus {
	if in == nil {
		return nil
	}
	out := new(BridgeInformationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressInterface) DeepCopyInto(out *EgressInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressInterface.
func (in *EgressInterface) DeepCopy() *EgressInterface {
	if in == nil {
		return nil
	}
	out := new(EgressInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressVlanInterface) DeepCopyInto(out *EgressVlanInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressVlanInterface.
func (in *EgressVlanInterface) DeepCopy() *EgressVlanInterface {
	if in == nil {
		return nil
	}
	out := new(EgressVlanInterface)
	in.DeepCopyInto(out)
	return out
}
