name: push-release
on:
  push:
    tags:
      - v*
jobs:
  push-release:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      REPOSITORY: ghcr.io/${{ github.repository }}
      IMAGE_OWNER: 'k8snetworkplumbingwg'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == env.IMAGE_OWNER }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: ${{ env.REPOSITORY }}
          tag-latest: false

      - name: Build controller image
        if: ${{ github.repository_owner == env.IMAGE_OWNER }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:stable
            ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64

      - name: Build bridge-operator-daemon image
        if: ${{ github.repository_owner == env.IMAGE_OWNER }}
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.daemon
          tags: |
            ghcr.io/${{ github.repository }}:stable-daemon
            ${{ steps.docker_meta.outputs.tags }}-daemon
          platforms: linux/amd64
